// Generated by scripts/update-spatial-skill-catalog.ts. Do not edit by hand.
// Source: SKILL-TREE-001 / companion Skill Tree Lab seed.
export const PLAYER_CHARACTER_CATALOG = {
  "catalogId": "nexus.skill-tree.provisional",
  "catalogVersion": "2026-07-16+48be6c31f0aa5d0f3353ce7faa96c2b2501e2236",
  "source": {
    "docId": "SKILL-TREE-001",
    "lastUpdated": "2026-07-16",
    "blob": "48be6c31f0aa5d0f3353ce7faa96c2b2501e2236"
  },
  "attributes": [
    {
      "id": "attribute-combat",
      "name": "Combat",
      "skills": [
        {
          "id": "skill-attribute-combat-firearms",
          "name": "Firearms",
          "focuses": [
            {
              "id": "focus-skill-attribute-combat-offense-precision-fire",
              "name": "Precision Fire",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-offense-precision-fire-steady-rifle",
                  "name": "Steady Rifle",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-offense-precision-fire-sightline-discipline",
                  "name": "Sightline Discipline",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-offense-precision-fire-converging-fire",
                  "name": "Converging Fire",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-combat-offense-precision-fire-steady-rifle",
                    "ability-focus-skill-attribute-combat-offense-precision-fire-sightline-discipline"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-combat-offense-sidearms",
              "name": "Sidearms",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-offense-sidearms-close-pistol",
                  "name": "Close Pistol",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-offense-sidearms-backup-shot",
                  "name": "Backup Shot",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-combat-close-combat",
          "name": "Close Combat",
          "focuses": [
            {
              "id": "focus-skill-attribute-combat-offense-breach-fighting",
              "name": "Breach Fighting",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-offense-breach-fighting-hard-contact",
                  "name": "Hard Contact",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-offense-breach-fighting-clinch-control",
                  "name": "Clinch Control",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-combat-heavy-weapons",
          "name": "Heavy Weapons",
          "focuses": [
            {
              "id": "focus-skill-attribute-combat-offense-heavy-weapons-use",
              "name": "Heavy Weapons Use",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-offense-heavy-weapons-use-big-gun-handling",
                  "name": "Big Gun Handling",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-offense-heavy-weapons-use-area-pressure",
                  "name": "Area Pressure",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-combat-field-defense",
          "name": "Field Defense",
          "focuses": [
            {
              "id": "focus-skill-attribute-combat-guard-armor-handling",
              "name": "Armor Handling",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-guard-armor-handling-brace-protocol",
                  "name": "Brace Protocol",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-armor-handling-controlled-impact",
                  "name": "Controlled Impact",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-combat-guard-interposition",
              "name": "Interposition",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-guard-interposition-screen-watch",
                  "name": "Screen Watch",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-interposition-guarded-passage",
                  "name": "Guarded Passage",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-interposition-take-the-hit",
                  "name": "Take the Hit",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-interposition-defended-corridor",
                  "name": "Defended Corridor",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-combat-guard-interposition-screen-watch",
                    "ability-focus-skill-attribute-combat-guard-interposition-guarded-passage"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-combat-guard-defensive-positioning",
              "name": "Defensive Positioning",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-guard-defensive-positioning-cover-drill",
                  "name": "Cover Drill",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-defensive-positioning-fighting-withdrawal",
                  "name": "Fighting Withdrawal",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-defensive-positioning-anchor-point",
                  "name": "Anchor Point",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-guard-defensive-positioning-hold-the-line",
                  "name": "Hold the Line",
                  "tier": 3,
                  "maxRank": 1,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-combat-guard-defensive-positioning-cover-drill",
                    "ability-focus-skill-attribute-combat-guard-defensive-positioning-anchor-point"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-combat-tactics",
          "name": "Tactics",
          "focuses": [
            {
              "id": "focus-skill-attribute-combat-command-suppression",
              "name": "Suppression",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-command-suppression-support-gunner",
                  "name": "Support Gunner",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-command-suppression-denial-pattern",
                  "name": "Denial Pattern",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-combat-command-target-calling",
              "name": "Target Calling",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-command-target-calling-call-angle",
                  "name": "Call Angle",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-command-target-calling-threat-ledger",
                  "name": "Threat Ledger",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-combat-command-field-direction",
              "name": "Field Direction",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-combat-command-field-direction-command-line",
                  "name": "Command Line",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-command-field-direction-split-second-reposition",
                  "name": "Split-Second Reposition",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-combat-command-field-direction-coordinated-tempo",
                  "name": "Coordinated Tempo",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-combat-command-field-direction-command-line",
                    "ability-focus-skill-attribute-combat-command-field-direction-split-second-reposition"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "attribute-dexterity",
      "name": "Dexterity",
      "skills": [
        {
          "id": "skill-attribute-dexterity-mobility",
          "name": "Mobility",
          "focuses": [
            {
              "id": "focus-skill-attribute-dexterity-mobility-rapid-transit",
              "name": "Rapid Transit",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-rapid-transit-quick-mover",
                  "name": "Quick Mover",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-rapid-transit-momentum-reserve",
                  "name": "Momentum Reserve",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-rapid-transit-impossible-route",
                  "name": "Impossible Route",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-dexterity-mobility-rapid-transit-quick-mover",
                    "ability-focus-skill-attribute-dexterity-mobility-rapid-transit-momentum-reserve"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-dexterity-mobility-terrain-movement",
              "name": "Terrain Movement",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-terrain-movement-power-traverse",
                  "name": "Power Traverse",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-terrain-movement-soft-landing",
                  "name": "Soft Landing",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-dexterity-mobility-zero-g-maneuvering",
              "name": "Zero-G Maneuvering",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-zero-g-maneuvering-vector-tuck",
                  "name": "Vector Tuck",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-mobility-zero-g-maneuvering-tether-logic",
                  "name": "Tether Logic",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-dexterity-infiltration",
          "name": "Infiltration",
          "focuses": [
            {
              "id": "focus-skill-attribute-dexterity-infiltration-concealment",
              "name": "Concealment",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-concealment-quiet-approach",
                  "name": "Quiet Approach",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-concealment-thermal-patience",
                  "name": "Thermal Patience",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-dexterity-infiltration-breachcraft",
              "name": "Breachcraft",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-breachcraft-silent-entry",
                  "name": "Silent Entry",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-breachcraft-lock-bypass",
                  "name": "Lock Bypass",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-dexterity-infiltration-counter-surveillance",
              "name": "Counter-Surveillance",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-counter-surveillance-dead-angle",
                  "name": "Dead Angle",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-counter-surveillance-trail-scrub",
                  "name": "Trail Scrub",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-infiltration-counter-surveillance-between-sensors",
                  "name": "Between Sensors",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-dexterity-infiltration-counter-surveillance-dead-angle",
                    "ability-focus-skill-attribute-dexterity-infiltration-counter-surveillance-trail-scrub"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-dexterity-piloting",
          "name": "Piloting",
          "focuses": [
            {
              "id": "focus-skill-attribute-dexterity-piloting-surface-vehicles",
              "name": "Surface Vehicles",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-surface-vehicles-drift-correction",
                  "name": "Drift Correction",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-surface-vehicles-hazard-line",
                  "name": "Hazard Line",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-dexterity-piloting-small-craft",
              "name": "Small Craft",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-small-craft-burn-window",
                  "name": "Burn Window",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-small-craft-docking-nerve",
                  "name": "Docking Nerve",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-small-craft-crew-coupled-maneuver",
                  "name": "Crew-Coupled Maneuver",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-dexterity-piloting-small-craft-burn-window",
                    "ability-focus-skill-attribute-dexterity-piloting-small-craft-docking-nerve"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-dexterity-piloting-remote-platforms",
              "name": "Remote Platforms",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-remote-platforms-proxy-hands",
                  "name": "Proxy Hands",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-remote-platforms-multi-feed-control",
                  "name": "Multi-Feed Control",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-dexterity-piloting-remote-platforms-no-safe-angle",
                  "name": "No Safe Angle",
                  "tier": 3,
                  "maxRank": 1,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-dexterity-piloting-remote-platforms-proxy-hands",
                    "ability-focus-skill-attribute-dexterity-piloting-remote-platforms-multi-feed-control"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "attribute-intelligence",
      "name": "Intelligence",
      "skills": [
        {
          "id": "skill-attribute-intelligence-computing",
          "name": "Computing",
          "focuses": [
            {
              "id": "focus-skill-attribute-intelligence-computing-intrusion",
              "name": "Intrusion",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-intrusion-clean-intrusion",
                  "name": "Clean Intrusion",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-intrusion-privilege-step",
                  "name": "Privilege Step",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-intrusion-cascading-access",
                  "name": "Cascading Access",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-intelligence-computing-intrusion-clean-intrusion",
                    "ability-focus-skill-attribute-intelligence-computing-intrusion-privilege-step"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-intelligence-computing-firewall",
              "name": "Firewall",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-firewall-shielded-kernel",
                  "name": "Shielded Kernel",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-firewall-quarantine-thread",
                  "name": "Quarantine Thread",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-intelligence-computing-electronic-warfare",
              "name": "Electronic Warfare",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-electronic-warfare-signal-drag",
                  "name": "Signal Drag",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-electronic-warfare-ghost-channel",
                  "name": "Ghost Channel",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-computing-electronic-warfare-systems-sovereignty",
                  "name": "Systems Sovereignty",
                  "tier": 3,
                  "maxRank": 1,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-intelligence-computing-electronic-warfare-signal-drag",
                    "ability-focus-skill-attribute-intelligence-computing-electronic-warfare-ghost-channel"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-intelligence-engineering",
          "name": "Engineering",
          "focuses": [
            {
              "id": "focus-skill-attribute-intelligence-engineering-field-repair",
              "name": "Field Repair",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-field-repair-field-restore",
                  "name": "Field Restore",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-field-repair-hot-swap",
                  "name": "Hot Swap",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-field-repair-restore-under-load",
                  "name": "Restore Under Load",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-intelligence-engineering-field-repair-field-restore",
                    "ability-focus-skill-attribute-intelligence-engineering-field-repair-hot-swap"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-intelligence-engineering-power-and-systems",
              "name": "Power and Systems",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-power-and-systems-load-balance",
                  "name": "Load Balance",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-power-and-systems-emergency-bypass",
                  "name": "Emergency Bypass",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-intelligence-engineering-structural-diagnostics",
              "name": "Structural Diagnostics",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-structural-diagnostics-failure-map",
                  "name": "Failure Map",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-engineering-structural-diagnostics-stress-echo",
                  "name": "Stress Echo",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-intelligence-fabrication",
          "name": "Fabrication",
          "focuses": [
            {
              "id": "focus-skill-attribute-intelligence-fabrication-field-assembly",
              "name": "Field Assembly",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-field-assembly-rapid-jig",
                  "name": "Rapid Jig",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-field-assembly-modular-build",
                  "name": "Modular Build",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-intelligence-fabrication-salvage-integration",
              "name": "Salvage Integration",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-salvage-integration-useful-ruin",
                  "name": "Useful Ruin",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-salvage-integration-foreign-interface",
                  "name": "Foreign Interface",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-intelligence-fabrication-precision-manufacture",
              "name": "Precision Manufacture",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-precision-manufacture-clean-tolerance",
                  "name": "Clean Tolerance",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-precision-manufacture-microforge-plan",
                  "name": "Microforge Plan",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-intelligence-fabrication-precision-manufacture-adaptive-toolchain",
                  "name": "Adaptive Toolchain",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-intelligence-fabrication-precision-manufacture-clean-tolerance",
                    "ability-focus-skill-attribute-intelligence-fabrication-precision-manufacture-microforge-plan"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "attribute-constitution",
      "name": "Constitution",
      "skills": [
        {
          "id": "skill-attribute-constitution-endurance",
          "name": "Endurance",
          "focuses": [
            {
              "id": "focus-skill-attribute-constitution-endurance-hazard-adaptation",
              "name": "Hazard Adaptation",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-hazard-adaptation-environmental-acclimation",
                  "name": "Environmental Acclimation",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-hazard-adaptation-seal-discipline",
                  "name": "Seal Discipline",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-hazard-adaptation-hostile-world-routine",
                  "name": "Hostile World Routine",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-constitution-endurance-hazard-adaptation-environmental-acclimation",
                    "ability-focus-skill-attribute-constitution-endurance-hazard-adaptation-seal-discipline"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-constitution-endurance-trauma-resistance",
              "name": "Trauma Resistance",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-trauma-resistance-stay-functional",
                  "name": "Stay Functional",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-trauma-resistance-pain-partition",
                  "name": "Pain Partition",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-constitution-endurance-sustained-exertion",
              "name": "Sustained Exertion",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-sustained-exertion-second-wind",
                  "name": "Second Wind",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-sustained-exertion-work-rhythm",
                  "name": "Work Rhythm",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-endurance-sustained-exertion-remain-viable",
                  "name": "Remain Viable",
                  "tier": 3,
                  "maxRank": 1,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-constitution-endurance-sustained-exertion-second-wind",
                    "ability-focus-skill-attribute-constitution-endurance-sustained-exertion-work-rhythm"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-constitution-medicine",
          "name": "Medicine",
          "focuses": [
            {
              "id": "focus-skill-attribute-constitution-medicine-combat-triage",
              "name": "Combat Triage",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-combat-triage-fast-patch",
                  "name": "Fast Patch",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-combat-triage-condition-read",
                  "name": "Condition Read",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-constitution-medicine-stabilization",
              "name": "Stabilization",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-stabilization-keep-them-breathing",
                  "name": "Keep Them Breathing",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-stabilization-safe-transfer",
                  "name": "Safe Transfer",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-stabilization-golden-minute",
                  "name": "Golden Minute",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-constitution-medicine-stabilization-keep-them-breathing",
                    "ability-focus-skill-attribute-constitution-medicine-stabilization-safe-transfer"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-constitution-medicine-field-recovery",
              "name": "Field Recovery",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-field-recovery-recovery-plan",
                  "name": "Recovery Plan",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-medicine-field-recovery-controlled-rest",
                  "name": "Controlled Rest",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-constitution-biotechnology",
          "name": "Biotechnology",
          "focuses": [
            {
              "id": "focus-skill-attribute-constitution-biointegration-adaptive-biotech",
              "name": "Adaptive Biotech",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-adaptive-biotech-adaptive-culture",
                  "name": "Adaptive Culture",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-adaptive-biotech-living-countermeasure",
                  "name": "Living Countermeasure",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-constitution-cybernetics",
          "name": "Cybernetics",
          "focuses": [
            {
              "id": "focus-skill-attribute-constitution-biointegration-cybernetic-care",
              "name": "Cybernetic Care",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-cybernetic-care-sleeve-tech",
                  "name": "Sleeve Tech",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-cybernetic-care-interface-flush",
                  "name": "Interface Flush",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-constitution-biointegration-body-modulation",
              "name": "Body Modulation",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-body-modulation-metabolic-shift",
                  "name": "Metabolic Shift",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-body-modulation-controlled-overclock",
                  "name": "Controlled Overclock",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-constitution-biointegration-body-modulation-symbiotic-interface",
                  "name": "Symbiotic Interface",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-constitution-biointegration-body-modulation-metabolic-shift",
                    "ability-focus-skill-attribute-constitution-biointegration-body-modulation-controlled-overclock"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "attribute-wisdom",
      "name": "Wisdom",
      "skills": [
        {
          "id": "skill-attribute-wisdom-perception",
          "name": "Perception",
          "focuses": [
            {
              "id": "focus-skill-attribute-wisdom-perception-threat-awareness",
              "name": "Threat Awareness",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-threat-awareness-pre-contact-read",
                  "name": "Pre-Contact Read",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-threat-awareness-watchful-rest",
                  "name": "Watchful Rest",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-wisdom-perception-sensor-interpretation",
              "name": "Sensor Interpretation",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-sensor-interpretation-cross-sensor-picture",
                  "name": "Cross-Sensor Picture",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-sensor-interpretation-noise-floor",
                  "name": "Noise Floor",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-sensor-interpretation-distributed-watch",
                  "name": "Distributed Watch",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-wisdom-perception-sensor-interpretation-cross-sensor-picture",
                    "ability-focus-skill-attribute-wisdom-perception-sensor-interpretation-noise-floor"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-wisdom-perception-search-and-tracking",
              "name": "Search and Tracking",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-search-and-tracking-trace-continuity",
                  "name": "Trace Continuity",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-perception-search-and-tracking-route-sign",
                  "name": "Route Sign",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-wisdom-cognition",
          "name": "Cognition",
          "focuses": [
            {
              "id": "focus-skill-attribute-wisdom-cognition-analysis",
              "name": "Analysis",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-analysis-failure-hypothesis",
                  "name": "Failure Hypothesis",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-analysis-operational-model",
                  "name": "Operational Model",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-wisdom-cognition-recall-and-dossiers",
              "name": "Recall and Dossiers",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-recall-and-dossiers-faction-recall",
                  "name": "Faction Recall",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-recall-and-dossiers-equipment-recognition",
                  "name": "Equipment Recognition",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-wisdom-cognition-pattern-synthesis",
              "name": "Pattern Synthesis",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-pattern-synthesis-anomaly-chain",
                  "name": "Anomaly Chain",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-pattern-synthesis-predictive-branch",
                  "name": "Predictive Branch",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-cognition-pattern-synthesis-counterfactual-map",
                  "name": "Counterfactual Map",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-wisdom-cognition-pattern-synthesis-anomaly-chain",
                    "ability-focus-skill-attribute-wisdom-cognition-pattern-synthesis-predictive-branch"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-wisdom-resolve",
          "name": "Resolve",
          "focuses": [
            {
              "id": "focus-skill-attribute-wisdom-resolve-stress-control",
              "name": "Stress Control",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-stress-control-steady-pulse",
                  "name": "Steady Pulse",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-stress-control-compartmentalize",
                  "name": "Compartmentalize",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-wisdom-resolve-identity-continuity",
              "name": "Identity Continuity",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-identity-continuity-self-anchor",
                  "name": "Self-Anchor",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-identity-continuity-memory-checksum",
                  "name": "Memory Checksum",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-wisdom-resolve-first-contact-grounding",
              "name": "First-Contact Grounding",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-unknown-protocol",
                  "name": "Unknown Protocol",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-meaning-quarantine",
                  "name": "Meaning Quarantine",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-continuity-under-contact",
                  "name": "Continuity Under Contact",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-unknown-protocol",
                    "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-meaning-quarantine"
                  ],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-witness-without-surrender",
                  "name": "Witness Without Surrender",
                  "tier": 3,
                  "maxRank": 1,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-unknown-protocol",
                    "ability-focus-skill-attribute-wisdom-resolve-first-contact-grounding-meaning-quarantine"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "attribute-charisma",
      "name": "Charisma",
      "skills": [
        {
          "id": "skill-attribute-charisma-negotiation",
          "name": "Negotiation",
          "focuses": [
            {
              "id": "focus-skill-attribute-charisma-rapport-terms-and-accord",
              "name": "Terms and Accord",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-terms-and-accord-common-terms",
                  "name": "Common Terms",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-terms-and-accord-leverage-window",
                  "name": "Leverage Window",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-terms-and-accord-bridge-the-divide",
                  "name": "Bridge the Divide",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-charisma-rapport-terms-and-accord-common-terms",
                    "ability-focus-skill-attribute-charisma-rapport-terms-and-accord-leverage-window"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-charisma-empathy",
          "name": "Empathy",
          "focuses": [
            {
              "id": "focus-skill-attribute-charisma-rapport-emotional-read",
              "name": "Emotional Read",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-emotional-read-read-the-room",
                  "name": "Read the Room",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-emotional-read-stabilizing-presence",
                  "name": "Stabilizing Presence",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-charisma-rapport-morale",
              "name": "Morale",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-morale-steady-voice",
                  "name": "Steady Voice",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-rapport-morale-shared-purpose",
                  "name": "Shared Purpose",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-charisma-deception",
          "name": "Deception",
          "focuses": [
            {
              "id": "focus-skill-attribute-charisma-influence-cover-and-misdirection",
              "name": "Cover and Misdirection",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-cover-and-misdirection-clean-lie",
                  "name": "Clean Lie",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-cover-and-misdirection-layered-cover",
                  "name": "Layered Cover",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-charisma-influence-performance",
              "name": "Performance",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-performance-commanding-persona",
                  "name": "Commanding Persona",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-performance-directed-distraction",
                  "name": "Directed Distraction",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-performance-controlled-frame",
                  "name": "Controlled Frame",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-charisma-influence-performance-commanding-persona",
                    "ability-focus-skill-attribute-charisma-influence-performance-directed-distraction"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-charisma-pressure",
          "name": "Pressure",
          "focuses": [
            {
              "id": "focus-skill-attribute-charisma-influence-credible-threat",
              "name": "Credible Threat",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-credible-threat-terms-of-pressure",
                  "name": "Terms of Pressure",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-influence-credible-threat-controlled-threat",
                  "name": "Controlled Threat",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        },
        {
          "id": "skill-attribute-charisma-networks",
          "name": "Networks",
          "focuses": [
            {
              "id": "focus-skill-attribute-charisma-networks-streetwise",
              "name": "Streetwise",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-streetwise-quiet-channels",
                  "name": "Quiet Channels",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-streetwise-local-procedure",
                  "name": "Local Procedure",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-charisma-networks-exchange",
              "name": "Exchange",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-exchange-fair-value",
                  "name": "Fair Value",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-exchange-salvage-broker",
                  "name": "Salvage Broker",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                }
              ]
            },
            {
              "id": "focus-skill-attribute-charisma-networks-faction-access",
              "name": "Faction Access",
              "abilities": [
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-faction-access-credential-read",
                  "name": "Credential Read",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-faction-access-call-in-context",
                  "name": "Call in Context",
                  "tier": 1,
                  "maxRank": 3,
                  "prerequisiteIds": [],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-faction-access-reciprocal-network",
                  "name": "Reciprocal Network",
                  "tier": 2,
                  "maxRank": 2,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-charisma-networks-faction-access-credential-read",
                    "ability-focus-skill-attribute-charisma-networks-faction-access-call-in-context"
                  ],
                  "prerequisiteLogic": "AND"
                },
                {
                  "id": "ability-focus-skill-attribute-charisma-networks-faction-access-accord-under-fire",
                  "name": "Accord Under Fire",
                  "tier": 3,
                  "maxRank": 1,
                  "prerequisiteIds": [
                    "ability-focus-skill-attribute-charisma-networks-faction-access-credential-read",
                    "ability-focus-skill-attribute-charisma-networks-faction-access-call-in-context"
                  ],
                  "prerequisiteLogic": "AND"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "sharedBranches": [
    {
      "id": "shared-interlock-drill",
      "name": "Interlock Drill",
      "skillIds": [
        "skill-attribute-combat-firearms",
        "skill-attribute-combat-tactics"
      ],
      "prerequisiteLogic": "AND",
      "abilities": [
        {
          "id": "ability-shared-interlock-drill-crossing-window",
          "name": "Crossing Window",
          "tier": 2,
          "maxRank": 2,
          "prerequisiteIds": [
            "ability-focus-skill-attribute-combat-offense-precision-fire-steady-rifle",
            "ability-focus-skill-attribute-combat-command-target-calling-call-angle"
          ],
          "prerequisiteLogic": "AND"
        }
      ]
    },
    {
      "id": "shared-extraction-window",
      "name": "Extraction Window",
      "skillIds": [
        "skill-attribute-dexterity-mobility",
        "skill-attribute-constitution-medicine"
      ],
      "prerequisiteLogic": "AND",
      "abilities": [
        {
          "id": "ability-shared-extraction-window-moving-casualty",
          "name": "Moving Casualty",
          "tier": 2,
          "maxRank": 2,
          "prerequisiteIds": [
            "ability-focus-skill-attribute-dexterity-mobility-rapid-transit-quick-mover",
            "ability-focus-skill-attribute-constitution-medicine-stabilization-safe-transfer"
          ],
          "prerequisiteLogic": "AND"
        }
      ]
    },
    {
      "id": "shared-mutual-cover-protocol",
      "name": "Mutual Cover Protocol",
      "skillIds": [
        "skill-attribute-combat-field-defense",
        "skill-attribute-combat-tactics"
      ],
      "prerequisiteLogic": "AND",
      "abilities": [
        {
          "id": "ability-shared-mutual-cover-protocol-leapfrog-guard",
          "name": "Leapfrog Guard",
          "tier": 2,
          "maxRank": 2,
          "prerequisiteIds": [
            "ability-focus-skill-attribute-combat-guard-interposition-screen-watch",
            "ability-focus-skill-attribute-combat-command-field-direction-command-line"
          ],
          "prerequisiteLogic": "AND"
        }
      ]
    },
    {
      "id": "shared-borrowed-authority",
      "name": "Borrowed Authority",
      "skillIds": [
        "skill-attribute-intelligence-computing",
        "skill-attribute-charisma-networks"
      ],
      "prerequisiteLogic": "OR",
      "abilities": [
        {
          "id": "ability-shared-borrowed-authority-provisional-credential",
          "name": "Provisional Credential",
          "tier": 2,
          "maxRank": 2,
          "prerequisiteIds": [
            "ability-focus-skill-attribute-intelligence-computing-intrusion-clean-intrusion",
            "ability-focus-skill-attribute-charisma-networks-faction-access-credential-read"
          ],
          "prerequisiteLogic": "OR"
        }
      ]
    },
    {
      "id": "shared-self-authored-form",
      "name": "Self-Authored Form",
      "skillIds": [
        "skill-attribute-constitution-cybernetics",
        "skill-attribute-wisdom-resolve"
      ],
      "prerequisiteLogic": "AND",
      "abilities": [
        {
          "id": "ability-shared-self-authored-form-consent-locked-modulation",
          "name": "Consent-Locked Modulation",
          "tier": 2,
          "maxRank": 2,
          "prerequisiteIds": [
            "ability-focus-skill-attribute-constitution-biointegration-body-modulation-controlled-overclock",
            "ability-focus-skill-attribute-wisdom-resolve-identity-continuity-self-anchor"
          ],
          "prerequisiteLogic": "AND"
        }
      ]
    },
    {
      "id": "shared-field-requisition",
      "name": "Field Requisition",
      "skillIds": [
        "skill-attribute-intelligence-fabrication",
        "skill-attribute-charisma-networks"
      ],
      "prerequisiteLogic": "OR",
      "abilities": [
        {
          "id": "ability-shared-field-requisition-right-tool-right-window",
          "name": "Right Tool, Right Window",
          "tier": 2,
          "maxRank": 2,
          "prerequisiteIds": [
            "ability-focus-skill-attribute-intelligence-fabrication-field-assembly-modular-build",
            "ability-focus-skill-attribute-charisma-networks-exchange-fair-value"
          ],
          "prerequisiteLogic": "OR"
        }
      ]
    }
  ]
} as const;
