import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { seedLabData } from "../artifacts/nexus-companion/src/features/skill-tree-lab/seed-data.ts";

const OUTPUT_PATH = resolve(
  "lib/spatial-runtime/src/playerCharacterCatalog.generated.ts",
);
const CATALOG_ID = "nexus.skill-tree.provisional";
const CATALOG_VERSION =
  "2026-07-16+48be6c31f0aa5d0f3353ce7faa96c2b2501e2236";

const ability = (value: (typeof seedLabData.attributes)[number]["skills"][number]["focuses"][number]["abilities"][number]) => ({
  id: value.id,
  name: value.name,
  tier: value.tier,
  maxRank: value.maxRank,
  prerequisiteIds: value.prerequisiteIds,
  prerequisiteLogic: value.prerequisiteLogic,
});

const catalog = {
  catalogId: CATALOG_ID,
  catalogVersion: CATALOG_VERSION,
  source: {
    docId: "SKILL-TREE-001",
    lastUpdated: "2026-07-16",
    blob: "48be6c31f0aa5d0f3353ce7faa96c2b2501e2236",
  },
  attributes: seedLabData.attributes.map((attribute) => ({
    id: attribute.id,
    name: attribute.name,
    skills: attribute.skills.map((skill) => ({
      id: skill.id,
      name: skill.name,
      focuses: skill.focuses.map((focus) => ({
        id: focus.id,
        name: focus.name,
        abilities: focus.abilities.map(ability),
      })),
    })),
  })),
  sharedBranches: seedLabData.sharedBranches.map((branch) => ({
    id: branch.id,
    name: branch.name,
    skillIds: branch.skillIds,
    prerequisiteLogic: branch.prerequisiteLogic,
    abilities: branch.abilities.map(ability),
  })),
};

const output = `// Generated by scripts/update-spatial-skill-catalog.ts. Do not edit by hand.\n` +
  `// Source: SKILL-TREE-001 / companion Skill Tree Lab seed.\n` +
  `export const PLAYER_CHARACTER_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;\n`;

if (process.argv.includes("--check")) {
  let existing = "";
  try {
    existing = readFileSync(OUTPUT_PATH, "utf8");
  } catch {
    // The mismatch message below covers a missing generated file.
  }
  if (existing !== output) {
    console.error("[update-spatial-skill-catalog] generated catalog is stale");
    process.exitCode = 1;
  } else {
    console.log("[update-spatial-skill-catalog] OK");
  }
} else {
  writeFileSync(OUTPUT_PATH, output);
  console.log(`[update-spatial-skill-catalog] wrote ${OUTPUT_PATH}`);
}
