import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { seedLabData } from "../artifacts/nexus-companion/src/features/skill-tree-lab/seed-data.ts";

const OUTPUT_PATH = resolve(
  "lib/spatial-runtime/src/playerCharacterCatalog.generated.ts",
);
const SOURCE_PATH = resolve(
  "docs/nexus-game-source/source/Skills/Current State/SKILL-TREE-001 - Provisional_Skill_Tree_Playtest_Model.md",
);
const CATALOG_ID = "nexus.skill-tree.provisional";
const SOURCE_BLOB = "48be6c31f0aa5d0f3353ce7faa96c2b2501e2236";

const source = readFileSync(SOURCE_PATH);
const sourceBlob = createHash("sha1")
  .update(Buffer.from(`blob ${source.byteLength}\0`))
  .update(source)
  .digest("hex");
if (sourceBlob !== SOURCE_BLOB)
  throw new Error(
    `SKILL-TREE-001 source blob changed: expected ${SOURCE_BLOB}, received ${sourceBlob}.`,
  );

const ability = (value: (typeof seedLabData.attributes)[number]["skills"][number]["focuses"][number]["abilities"][number]) => ({
  id: value.id,
  name: value.name,
  tier: value.tier,
  maxRank: value.maxRank,
  prerequisiteIds: value.prerequisiteIds,
  prerequisiteLogic: value.prerequisiteLogic,
});

const catalogContent = {
  catalogId: CATALOG_ID,
  source: {
    docId: "SKILL-TREE-001",
    lastUpdated: "2026-07-16",
    blob: SOURCE_BLOB,
  },
  attributes: seedLabData.attributes.map((attribute) => ({
    id: attribute.id,
    name: attribute.name,
    skills: attribute.skills.map((skill) => ({
      id: skill.id,
      name: skill.name,
      focuses: skill.focuses.map((focus) => ({
        id: focus.id,
        name: focus.name,
        abilities: focus.abilities.map(ability),
      })),
    })),
  })),
  sharedBranches: seedLabData.sharedBranches.map((branch) => ({
    id: branch.id,
    name: branch.name,
    skillIds: branch.skillIds,
    prerequisiteLogic: branch.prerequisiteLogic,
    abilities: branch.abilities.map(ability),
  })),
};
const catalogVersion = `sha256:${createHash("sha256")
  .update(JSON.stringify(catalogContent))
  .digest("hex")}`;
const catalog = { ...catalogContent, catalogVersion };

const output = `// Generated by scripts/update-spatial-skill-catalog.ts. Do not edit by hand.\n` +
  `// Source: SKILL-TREE-001 / companion Skill Tree Lab seed.\n` +
  `import type { PlayerCharacterCatalog } from "./types.js";\n\n` +
  `export const PLAYER_CHARACTER_CATALOG: PlayerCharacterCatalog = ${JSON.stringify(catalog, null, 2)} as const;\n`;

if (process.argv.includes("--check")) {
  let existing = "";
  try {
    existing = readFileSync(OUTPUT_PATH, "utf8");
  } catch {
    // The mismatch message below covers a missing generated file.
  }
  if (existing !== output) {
    console.error("[update-spatial-skill-catalog] generated catalog is stale");
    process.exitCode = 1;
  } else {
    console.log("[update-spatial-skill-catalog] OK");
  }
} else {
  writeFileSync(OUTPUT_PATH, output);
  console.log(`[update-spatial-skill-catalog] wrote ${OUTPUT_PATH}`);
}
